[build]
  command = "yarn rw db up --no-db-client && yarn rw build"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "https://5e86b1c66b57b100064273e2--peaceful-hawking-f47563.netlify.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}