[build]
  command = "yarn rw db up --no-db-client && yarn rw build"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "https://accounts.spotify.com/api/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}